pypi-publish:
  image: python:latest
  script:
    - python -V
    - pip install virtualenv
    - virtualenv venv
    - source venv/bin/activate
    - pip install -U pip setuptools wheel
    - python setup.py sdist bdist_wheel
    - pip install twine
    - twine upload dist/*
  artifacts:
    paths:
      - dist/*.whl
  only:
    - tags
