site_name: "NPD Tools"
repo_url: https://github.com/whiteapfel/npdtools

theme:
  name: "material"
  language: ru
#  custom_dir: 'docs/theme'
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep orange
      accent: deep orange
      toggle:
        icon: material/lightbulb-outline
        name: "Затемнить"
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep orange
      accent: deep orange
      toggle:
        icon: material/lightbulb
        name: "Осветлить"
  features:
    - content.tabs.link
    - content.code.annotate
    - announce.dismiss
    - navigation.tabs
nav:
- Гайд:
  - Главная: index.md
  - Установка: guide/installation.md
  - Примеры: guide/example.md
- API:
  - Modules (Модули): API/modules.md
  - Types (Модели): API/types.md


plugins:
- search
- mkdocstrings:
    handlers:
      python:
        options:
          docstring_style: google
          show_if_no_docstring: false
          members_order: source
          show_symbol_type_heading: true
          docstring_options:
            ignore_init_summary: true
